updated emissions documentation
urbanopt/urbanopt.github.io pull request #172
Opened 2022-06-22 08:36 UTC by rawadelkontar

### Addresses #

### Pull Request Description

### Checklist

- [ ] Documentation has been modified appropriately
- [ ] An ISSUE has been created that this is addressing. Issues will get added to the Change Log when the change_log.rb script is run
- [ ] This branch is up-to-date with develop

2022-06-22 14:46 UTC, nllong requested changes
few tweaks. I'm sure I missed some orthographic updates, so a thorough review is recommended.

2022-06-22 14:46 UTC, nllong commented on workflows/carbon_emissions.md
> +	Fueloil #2 : 294.962046 KG/MWH
```suggestion
	Fuel oil #2 : 294.962046 KG/MWH
```

2022-06-22 14:46 UTC, nllong commented on workflows/carbon_emissions.md
> +Emissions results are reported in URBANopt reports. For each feature, timeseries results are reported in the CSV report and aggregate values are reported in URBANopt JSON reports. Bellow are descript
```suggestion
Emissions results are reported in URBANopt reports. For each feature, time series results are reported in the CSV report and aggregate values are reported in URBANopt JSON reports. Below are descriptions for the emissions results variables.
```

2022-06-22 14:46 UTC, nllong commented on workflows/carbon_emissions.md
> +	Historical electricity emissions intensity in kg.ft2 calculated based on hourly emissions factor values for the selected historical year
```suggestion
	Historical electricity emissions intensity in kg/ft2 calculated based on hourly emissions factor values for the selected historical year
```

2022-06-22 14:46 UTC, nllong commented on workflows/carbon_emissions.md
> +	Natural Gas emissions in mt calculated by multipling the facility natural gas energy use (MWH) by the natural gas emission factor (277.358126 KG/MWH) and convertd to metric ton(mt)
```suggestion
	Natural Gas emissions in metric tonnes (mt) were calculated by multiplying the facility's natural gas energy use (MWh) by the natural gas emission factor (277.4 kg/MWH) and converted to metric tonnes (mt)
```
I think tonnes is the right spelling here? Or maybe not. Another opinion is probably needed.

2022-06-23 18:44 UTC, kflemin approved these changes

2022-06-23 18:44 UTC, kflemin commented on workflows/carbon_emissions.md
> +The following documents the capabilities added to URBANopt&trade; to calculate carbon emissions associated with building electricity, natural gas, propane and fuel oil number 1 use.
Number 2 or number 1?

2022-06-23 19:11 UTC, nllong commented on workflows/carbon_emissions.md
> +	natural gas :  277.358126 KG/MWH
```suggestion
	natural gas :  277.358126 kg/MWh
```

is this suppose to be kg/MWh? I'm not sure what KG/MWH is. @rawadelkontar

2022-06-28 20:50 UTC, merged